### ISSUE TITLE
Cannot import my `endsong_X.json` files

### ISSUE THREAD

**Issue by johan-lejdung** [Yooooomi/your_spotify#103]
**Describe the bug**
I've requested the full data output from Spotify, and when I try to import the files I get no errors in the client. However if I inspect the logs I get a bunch of errors such as those described below.

**Expected behavior**
I expected an import to start

**Additional context**

Snippet from my endsong_0.json file (with some information redacted)

```
[{"ts":"2016-05-30T15:48:22Z","username":"<REMOVED>","platform":"Android OS 6.0.1 API 23 (LGE, Nexus 5)","ms_played":570036,"conn_country":"<2LETTERISOCODE>","ip_addr_decrypted":"<REMOVED>","user_agent_decrypted":"unknown","master_metadata_track_name":"Healing Thunderstorm with Light Rain","master_metadata_album_artist_name":"Nature Sounds","master_metadata_album_album_name":"Thunderstorms - Sounds of Nature","spotify_track_uri":"spotify:track:50s6l2Rq0EHowZsiFV1fQ0","episode_name":null,"episode_show_name":null,"spotify_episode_uri":null,"reason_start":"trackdone","reason_end":"trackdone","shuffle":true,"skipped":null,"offline":false,"offline_timestamp":0,"incognito_mode":false},{"ts":"2014-02-13T11:05:48Z","username":"<REMOVED>","platform":"Windows 7 (6.1.7601; x64; SP1; S)","ms_played":223085,"conn_country":"<2LETTERISOCODE>","ip_addr_decrypted":"<REMOVED>","user_agent_decrypted":"unknown","master_metadata_track_name":"Thirteen Thirty-Five","master_metadata_album_artist_name":"Dillon","master_metadata_album_album_name":"This Silence Kills","spotify_track_uri":"spotify:track:3N2vr4m44BBZiVCZ0O4bnf","episode_name":null,"episode_show_name":null,"spotify_episode_uri":null,"reason_start":"trackdone","reason_end":"trackdone","shuffle":false,"skipped":false,"offline":false,"offline_timestamp":0,"incognito_mode":false},{"ts":"2012-12-20T12:01:30Z","username":"<REMOVED>","platform":"Windows Vista (Unknown Ed) SP0 [x86 0]","ms_played":3157,"conn_country":"<2LETTERISOCODE>","ip_addr_decrypted":"<REMOVED>","user_agent_decrypted":"unknown","master_metadata_track_name":"Brandenburg Concerto No. 1 in F Major, BWV 1046: II. Adagio - Allegro","master_metadata_album_artist_name":"Johann Sebastian Bach","master_metadata_album_album_name":"Vivaldi, Bach, Marcello & Telemann: Concertos for Oboe and Orchesrta","spotify_track_uri":"spotify:track:4l1PgS6cPuC4KzUfFx486Z","episode_name":null,"episode_show_name":null,"spotify_episode_uri":null,"reason_start":"popup","reason_end":"clickside","shuffle":false,"skipped":true,"offline":false,"offline_timestamp":0,"incognito_mode":false},...
```

Server Logs:

```
at new ZodError (/app/node_modules/zod/lib/ZodError.js:81:28)
    at handleResult (/app/node_modules/zod/lib/types.js:115:21)
    at ZodArray.ZodType.safeParse (/app/node_modules/zod/lib/types.js:210:16)
    at ZodArray.ZodType.parse (/app/node_modules/zod/lib/types.js:191:27)
    at FullPrivacyImporter.<anonymous> (/app/lib/tools/importers/full_privacy.js:71:59)
    at Generator.next (<anonymous>)
    at /app/lib/tools/importers/full_privacy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/lib/tools/importers/full_privacy.js:4:12)
    at FullPrivacyImporter.initWithJSONContent (/app/lib/tools/importers/full_privacy.js:69:49) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    {
      code: 'invalid_type',
      expected: 'boolean',
      received: 'null',
      path: [Array],
      message: 'Expected boolean, received null'
    },
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'null',
      path: [Array],
      message: 'Expected number, received null'
    },
    ... 4022 more items
  ],
  format: [Function (anonymous)],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)]
}
[error]  TypeError: Cannot read properties of null (reading 'length')
    at FullPrivacyImporter.<anonymous> (/app/lib/tools/importers/full_privacy.js:98:51)
    at Generator.next (<anonymous>)
    at fulfilled (/app/lib/tools/importers/full_privacy.js:5:58)
POST /inform 404 1.241 ms - 146
```

**Screenshots**
After upload fails in client side
<img width="702" alt="Screenshot 2022-03-09 at 23 12 53" src="https://user-images.githubusercontent.com/9266884/157545330-97f4b82d-36e7-4a14-88d6-a1538755387c.png">

**Comment by Yooooomi** [comment]
Hello, for privacy, could you send me your files through discord @ Marvin the Martian#8336? There must be some field that has a null value where I expect someting else.

**Comment by johan-lejdung** [comment]
Absolutely, I have 13 files but can start sending you the first one.

**Comment by Yooooomi** [comment]
It should now be fixed in the latest version. Please close this issue if you successfully start your import using your files :)

**Comment by johan-lejdung** [comment]
Fantastic. First file is now importing, I'm going to go through all 13 during this weekend and let you know if there are any issues :)

**Comment by johan-lejdung** [comment]
Started off with file 1, worked great. Seems like the rest works as well! 7 years of listening history currently importing :)

<img width="694" alt="Screenshot 2022-03-12 at 12 20 56" src="https://user-images.githubusercontent.com/9266884/158016048-ba261d4b-fc81-481b-9aff-3ac5c062b1ff.png">

**Comment by johan-lejdung** [comment]
Seems it failed again: 
<img width="671" alt="Screenshot 2022-03-12 at 12 55 46" src="https://user-images.githubusercontent.com/9266884/158017019-67e5c480-c6b4-4c86-93a9-f0929fea00da.png">

The error I'm getting is:

```
[error]  TypeError: data[arrayPath] is not iterable (cannot read property undefined)
    at /app/lib/spotify/dbTools.js:29:15
    at Generator.next (<anonymous>)
    at fulfilled (/app/lib/spotify/dbTools.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error]  This import failed, but metadata is kept so that you can retry it later in the settings
```

This line seems to be the issue: https://github.com/Yooooomi/your_spotify/blob/9c1439a2da99135b740a08cd6cd4d5e1aa62bd00/server/src/spotify/dbTools.ts#L33

Maybe change to:
```
if (data) { datas.push(...data[arrayPath]); }
```

Or always make sure that `() => squeue.queue((client) => client.get(builtUrl), userId)`, returns a valid value. Thoughts?

**Comment by johan-lejdung** [comment]
Worked when I retried the import, so I'll close this for now. Could just have been a fluke or network issue. Although would be good with some retry logic here I guess
