### ISSUE TITLE
oauth error and give 502

### ISSUE THREAD

**Issue by slikie** [Yooooomi/your_spotify#106]
**Describe the bug**
open site, click login, authenticate on spotify, 502 error on redirect.

**Additional context**

```
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:      - "13132:8080"
    environment:
      - API_ENDPOINT=https://spo1.domain
      - CLIENT_ENDPOINT=https://spo.domain
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - MONGO_ENDPOINT=mongodb+srv://
      - CORS=all
  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "13131:3000"
    environment:
      - API_ENDPOINT=https://spo1.domain

spo.domain:443 {
        reverse_proxy 127.0.0.1:13131
}
spo1.domain:443 {
        reverse_proxy 127.0.0.1:13132
}

spotify dashboard redirect URI - https://spo1.domain/oauth/spotify/callback

```

```

server_1  | [info]  Connected to database !
server_1  | [info]  Starting migrations
server_1  | [info]  Migrations successfully ran
server_1  | Done in 2.73s.
server_1  | yarn run v1.22.17
server_1  | $ node lib/bin/www
server_1  | [info]  Trying to connect to database at mongodb+srv://
server_1  | [info]  Connected to database !
server_1  | [info]  Checking database...
server_1  | [warn]  No user is admin, cannot auto fix database
server_1  | [info]  Starting loop for 0 users

server_1  | GET /oauth/spotify 302 2.096 ms - 294                                                                       
server_1  | GET /oauth/spotify 302 3.074 ms - 612                                                                       
server_1  | /app/node_modules/axios/lib/core/createError.js:16                                                          
server_1  |   var error = new Error(message);                                                                           
server_1  |               ^                                                                                             
server_1  |                                                                                                             
server_1  | Error: Request failed with status code 400                                                                  
server_1  |     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)                                  server_1  |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)                                            
server_1  |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:322:11)                
server_1  |     at IncomingMessage.emit (node:events:532:35)                                                            
server_1  |     at endReadableNT (node:internal/streams/readable:1346:12)                                               
server_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {                                
server_1  |   config: {                                                               
server_1  |     transitional: {                                                                                         
server_1  |       silentJSONParsing: true,                                                                              
server_1  |       forcedJSONParsing: true,                                                                              
server_1  |       clarifyTimeoutError: false                                                                            
server_1  |     },                                                                                                      
server_1  |     adapter: [Function: httpAdapter],                                                                       
server_1  |     transformRequest: [ [Function: transformRequest] ],                                                     
server_1  |     transformResponse: [ [Function: transformResponse] ],                                                   
server_1  |     timeout: 0,                                                                                             
server_1  |     xsrfCookieName: 'XSRF-TOKEN',                                                                           server_1  |     xsrfHeaderName: 'X-XSRF-TOKEN',                                                                         
server_1  |     maxContentLength: -1,                                                                                   
server_1  |     maxBodyLength: -1,                                                                                      
server_1  |     validateStatus: [Function: validateStatus],                                                             
server_1  |     headers: {                                                                                              
server_1  |       Accept: 'application/json, text/plain, */*',                                                          
server_1  |       'Content-Type': 'application/x-www-form-urlencoded',                                                  
server_1  |       'User-Agent': 'axios/0.26.0'                                                                          server_1  |     },                                                                                                      
server_1  |     params: {                                                                                               
server_1  |       grant_type: 'authorization_code',                    
server_1  |       code: 'some code',
server_1  |         redirect_uri: 'https://spo1.domainz/oauth/spotify/callback',                                    
server_1  |         client_id: '',                                                      
server_1  |         client_secret: ''                                                   
server_1  |       },                                                                                                    
server_1  |       method: 'post',                                                                                       
server_1  |       url: 'https://accounts.spotify.com/api/token',                                                        
server_1  |       data: null                                                                                            
server_1  |     },                                                                                                      server_1  |     request: <ref *2> ClientRequest {                                                                       
server_1  |  
server_1  |           pathname: '/api/token',             
server_1  |           search: '?grant_type=authorization_code&code=coderedirect_uri=https:%2F%2Fspo1.domain%2Foauth%2Fspotify%2Fcallback&client_id=code
&client_secret=code',   
```

**Screenshots**

**Comment by Yooooomi** [comment]
Hello!
A 502 error usually comes from your reverse proxy. Be sure to have the right configuration. Is it a caddy file?

**Comment by slikie** [comment]
Yes the related caddyfile included 

```

spo.domain:443 {
        reverse_proxy 127.0.0.1:13131
}
spo1.domain:443 {
        reverse_proxy 127.0.0.1:13132
}
```

**Comment by slikie** [comment]
Probably issue from Spotify end, it works with no changes after some hours.
