### ISSUE TITLE
Docker mongodb crash

### ISSUE THREAD

**Issue by Zyplonox** [Yooooomi/your_spotify#126]
Hi,

my mongodb container is crashing continually after a while. If i restart the app, it is doing well but after like 1-2 hours the container starts crashing.

docker log: 
```
/app/node_modules/mongoose/lib/connection.js:807
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:807:32)
    at /app/node_modules/mongoose/lib/index.js:342:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1181:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:341:20)
    at /app/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'mongo', port: 27017 },
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 86673340,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:375:20)
            at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:295:22)
            at Object.onceWrapper (node:events:642:26)
            at Socket.emit (node:events:527:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21) {
          [Symbol(errorLabels)]: Set(0) {}
        }
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined
}
error Command failed with exit code 1.
```
Regards

**Comment by Yooooomi** [comment]
Hello, can you post your docker-compose file please?
