### ISSUE TITLE
Could not retrive global prefrences error and loading error when connecting to login

### ISSUE THREAD

**Issue by trbntwo** [Yooooomi/your_spotify#150]
When i go to your spotify i get a red error message at the top with "Could not retrive global prefrences" and when i press login i am redirected however the website cannot be displayed and firefox displays:

Error: connection failed
Firefox cannot connect to the server at local-ip:8061.
The website might be temporarily unavailable, please try again later.
If you are also unable to access any other website, please check your network/Internet connection.
If your computer or network is protected by a firewall or proxy, please make sure Firefox is allowed to access the Internet.

In the private window and Chromium based browsers this is also the case.

In a similar issue it said that this is related to headers and what else is hosted on the home network, however I have no idea about this and no approach to solve this at all. Otherwise I host Nginx Proxy Manager, Nextcloud, OnlyOffice & Jellyfin all via Docker.

My docker-compose.yml file:
```
version: '3'

services:

  YourSpotify-Server:
    image: yooooomi/your_spotify_server
    container_name: YourSpotify-Server
    hostname: YourSpotify-Server
    restart: unless-stopped
    ports:
      - '8061:8080'
    links:
      - MongoDB
    depends_on:
      - MongoDB
    environment:
      - API_ENDPOINT=http://local-ip:8061 # This MUST be included as a valid URL in the spotify dashboard (see below)
      - CLIENT_ENDPOINT=http://local-ip:8062
      - SPOTIFY_PUBLIC=X
      - SPOTIFY_SECRET=X
      - CORS=all
      - TIMEZONE=Europe/Berlin

  MongoDB:
    image: mongo:4.4.8
    container_name: MongoDB-YS
    hostname: MongoDB-YS
    restart: unless-stopped
    volumes:
      - /home/Docker/YourSpotify:/data/db

  YourSpotify-Web:
    image: yooooomi/your_spotify_client
    container_name: YourSpotify-Web
    hostname: YourSpotify-Web
    restart: unless-stopped
    ports:
      - '8062:3000'
    environment:
      - API_ENDPOINT=http://local-ip:8061

**Comment by Yooooomi** [comment]
Heyy, i cannot fond something wrong in your configuration file. Can you send me the docker logs and the browser logs too please?

**Comment by trbntwo** [comment]
Hello,
sure:

YourSpotify-Server
```
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/node_modules/mongoose/lib/connection.js:807
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connection timed out
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:807:32)
    at /app/node_modules/mongoose/lib/index.js:342:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1181:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:341:20)
    at /app/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'mongo', port: 27017 },
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 596046,
        lastWriteDate: 0,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:377:20)
            at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:295:22)
            at Object.onceWrapper (node:events:641:28)
            at Socket.emit (node:events:527:28)
            at Socket._onTimeout (node:net:516:8)
            at listOnTimeout (node:internal/timers:559:17)
            at processTimers (node:internal/timers:502:7) {
          [Symbol(errorLabels)]: Set(0) {}
        }
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/node_modules/mongoose/lib/connection.js:807
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connection timed out
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:807:32)
    at /app/node_modules/mongoose/lib/index.js:342:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1181:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:341:20)
    at /app/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'mongo', port: 27017 },
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 630306,
        lastWriteDate: 0,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:377:20)
            at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:295:22)
            at Object.onceWrapper (node:events:641:28)
            at Socket.emit (node:events:527:28)
            at Socket._onTimeout (node:net:516:8)
            at listOnTimeout (node:internal/timers:559:17)
            at processTimers (node:internal/timers:502:7) {
          [Symbol(errorLabels)]: Set(0) {}
        }
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/node_modules/mongoose/lib/connection.js:807
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connection timed out
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:807:32)
    at /app/node_modules/mongoose/lib/index.js:342:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1181:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:341:20)
    at /app/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'mongo', port: 27017 },
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 664578,
        lastWriteDate: 0,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:377:20)
            at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:295:22)
            at Object.onceWrapper (node:events:641:28)
            at Socket.emit (node:events:527:28)
            at Socket._onTimeout (node:net:516:8)
            at listOnTimeout (node:internal/timers:559:17)
            at processTimers (node:internal/timers:502:7) {
          [Symbol(errorLabels)]: Set(0) {}
        }
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/node_modules/mongoose/lib/connection.js:807
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connection timed out
    at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:807:32)
    at /app/node_modules/mongoose/lib/index.js:342:10
    at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1181:10)
    at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:341:20)
    at /app/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'mongo', port: 27017 },
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 698796,
        lastWriteDate: 0,
        error: MongoNetworkTimeoutError: connection timed out
            at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:377:20)
            at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:295:22)
            at Object.onceWrapper (node:events:641:28)
            at Socket.emit (node:events:527:28)
            at Socket._onTimeout (node:net:516:8)
            at listOnTimeout (node:internal/timers:559:17)
            at processTimers (node:internal/timers:502:7) {
          [Symbol(errorLabels)]: Set(0) {}
        }
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined
}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

MongoDB
```
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

{"t":{"$date":"2022-08-13T13:53:14.229+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2022-08-13T13:53:14.232+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2022-08-13T13:53:14.232+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2022-08-13T13:53:14.233+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"MongoDB-YS"}}
{"t":{"$date":"2022-08-13T13:53:14.233+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.8","gitVersion":"83b8bb8b6b325d8d8d3dfd2ad9f744bdad7d6ca0","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2022-08-13T13:53:14.233+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
{"t":{"$date":"2022-08-13T13:53:14.233+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
{"t":{"$date":"2022-08-13T13:53:14.234+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
{"t":{"$date":"2022-08-13T13:53:14.234+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=31641M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2022-08-13T13:53:15.118+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:118221][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 1 through 2"}}
{"t":{"$date":"2022-08-13T13:53:15.187+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:187962][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 2"}}
{"t":{"$date":"2022-08-13T13:53:15.259+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:259412][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 1/24448 to 2/256"}}
{"t":{"$date":"2022-08-13T13:53:15.309+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:308998][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 1 through 2"}}
{"t":{"$date":"2022-08-13T13:53:15.351+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:351060][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 2"}}
{"t":{"$date":"2022-08-13T13:53:15.374+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:374584][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
{"t":{"$date":"2022-08-13T13:53:15.374+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:374624][1:0x7f9faab53cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
{"t":{"$date":"2022-08-13T13:53:15.377+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1660398795:377662][1:0x7f9faab53cc0], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 1, snapshot max: 1 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 6"}}
{"t":{"$date":"2022-08-13T13:53:15.391+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":1157}}
{"t":{"$date":"2022-08-13T13:53:15.391+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2022-08-13T13:53:15.393+00:00"},"s":"I",  "c":"STORAGE",  "id":4366408, "ctx":"initandlisten","msg":"No table logging settings modifications are required for existing WiredTiger tables","attr":{"loggingEnabled":true}}
{"t":{"$date":"2022-08-13T13:53:15.394+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
{"t":{"$date":"2022-08-13T13:53:15.412+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
{"t":{"$date":"2022-08-13T13:53:15.415+00:00"},"s":"I",  "c":"STORAGE",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
{"t":{"$date":"2022-08-13T13:53:15.418+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
{"t":{"$date":"2022-08-13T13:53:15.420+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
{"t":{"$date":"2022-08-13T13:53:15.421+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
{"t":{"$date":"2022-08-13T13:53:15.421+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
{"t":{"$date":"2022-08-13T13:54:15.395+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1660398855:395876][1:0x7f9fa3b44700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2022-08-13T13:55:15.420+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1660398915:420046][1:0x7f9fa3b44700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 5, snapshot max: 5 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2022-08-13T13:56:15.435+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1660398975:435255][1:0x7f9fa3b44700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 6, snapshot max: 6 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2022-08-13T13:57:15.455+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1660399035:455705][1:0x7f9fa3b44700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 7, snapshot max: 7 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}

```

YourSpotify-Web:
```
Setting API Endpoint to 'http://192.168.178.201:8061'
UPDATE AVAILABLE The latest version of `serve` is 14.0.1
INFO: Accepting connections at http://0.0.0.0:3000
```

Browser logs will follow

**Comment by trbntwo** [comment]
Browser logs:

```
Object { message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest, response: XMLHttpRequest, stack: "" }
thunk.ts:14:14
    e Redux
    Babel 9
    Redux 8
    t Wrapper.tsx:51
    Babel 9
    t Wrapper.tsx:48
    sh Wrapper.tsx:48
    sh Wrapper.tsx:55
    React 3
    k scheduler.production.min.js:13
    M scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    6813 scheduler.production.min.js:14
    Webpack 12
Object { message: "Network Error", name: "AxiosError", code: "ERR_NETWORK", config: {…}, request: XMLHttpRequest, response: XMLHttpRequest, stack: "" }
thunk.ts:13:14
    e Redux
    Babel 9
    Redux 9
    t Wrapper.tsx:52
    Babel 11
    t Wrapper.tsx:48
    sh Wrapper.tsx:48
    sh Wrapper.tsx:55
    React 3
    k scheduler.production.min.js:13
    M scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    6813 scheduler.production.min.js:14
    Webpack 12
```

**Comment by Yooooomi** [comment]
It seems that your server cannot connect to mongo, since you renamed the mongo container, you have to use the `MONGO_ENDPOINT` env variable to suit the name of your container. You have an example on the readme.

**Comment by trbntwo** [comment]
It worked with the enviroment variable '''MONGO_ENDPOINT``` and my custom name thank you very much!
