### ISSUE TITLE
MongoServerError: PlanExecutor error during aggregation :: caused by :: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#272]
**Describe the bug**

MongoDB ran out of memory limit for $group and allowDiskUse is not passed.

**Expected behavior**

I expected it to work like normal

**Additional context**

```
[info]  Checking database...
/app/node_modules/mongodb/lib/cmap/connection.js:202
                callback(new error_1.MongoServerError(document));
                         ^

MongoServerError: PlanExecutor error during aggregation :: caused by :: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28) {
  ok: 0,
  code: 292,
  codeName: 'QueryExceededMemoryLimitNoDiskUseAllowed',
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by samip5** [comment]
Hi @Yooooomi, this prevents the whole thing from properly starting up, and I believe it's version 1.7.0.

**Comment by Yooooomi** [comment]
Damn. I'll check which calls are using a group at the start of the app. I don't remember adding new requests to 1.7.0

**Comment by samip5** [comment]
> Damn. I'll check which calls are using a group at the start of the app. I don't remember adding new requests to 1.7.0

I'm not even sure if it has to do with 1.7.0 or if it's been there for a while but it just happens to run into it now.

**Comment by samip5** [comment]
@Yooooomi Any ideas on fixes to this?

**Comment by Yooooomi** [comment]
Hello! Sorry I've been on vacation I had no time to look at this. My first thoughts would be to check the check functions at startup to see if there are any group used there.

**Comment by Yooooomi** [comment]
Hey, I was looking at this issue but I feel like I already solved it in 1.7.1, could you confirm?

**Comment by Slitzo3** [comment]
Hello,  I'm getting this error when i'm trying to run affinity with other people on my instance

```
[error]  MongoServerError: PlanExecutor error during aggregation :: caused by :: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.,
    at Connection.sendCommand (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:297:27),
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
    at async Connection.command (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:325:26),
    at async Server.command (/app/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:166:24),
    at async AggregateOperation.executeCommand (/app/node_modules/mongoose/node_modules/mongodb/lib/operations/command.js:74:16),
    at async AggregateOperation.execute (/app/node_modules/mongoose/node_modules/mongodb/lib/operations/aggregate.js:85:21),
    at async executeOperation (/app/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:136:16),
    at async AggregationCursor._initialize (/app/node_modules/mongoose/node_modules/mongodb/lib/cursor/aggregation_cursor.js:46:26),
    at async [kInit] (/app/node_modules/mongoose/node_modules/mongodb/lib/cursor/abstract_cursor.js:463:27),
    at async next (/app/node_modules/mongoose/node_modules/mongodb/lib/cursor/abstract_cursor.js:520:13) {,
  errorResponse: {,
    ok: 0,,
    errmsg: "PlanExecutor error during aggregation :: caused by :: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.",,
    code: 292,,
    codeName: 'QueryExceededMemoryLimitNoDiskUseAllowed',
  },,
  ok: 0,,
  code: 292,,
  codeName: 'QueryExceededMemoryLimitNoDiskUseAllowed',,
  [Symbol(errorLabels)]: Set(0) {},
},
```
