### ISSUE TITLE
Black screen when I login

### ISSUE THREAD

**Issue by MiisterChipsSs** [Yooooomi/your_spotify#295]
**Describe the bug**

I installed the software, connected successfully and everything works behind a nginx proxy manager. But after a few hours, when I go back to it, I see the interface for a brief moment, then it disappears, leaving me with a black screen.

**Additional context**

Error from my chrome : 

`TypeError: Cannot read properties of null (reading 'images')
    at KW (Track.tsx:77:12)
    at ja (react-dom.production.min.js:167:137)
    at js (react-dom.production.min.js:290:337)
    at xu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at yu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)`

`Track.tsx:77 Uncaught TypeError: Cannot read properties of null (reading 'images')
    at KW (Track.tsx:77:12)
    at ja (react-dom.production.min.js:167:137)
    at js (react-dom.production.min.js:290:337)
    at xu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at yu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)`

I use the stack portainer

`version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: unless-stopped
    ports:
      - "${__api_port__}:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=${__api_endpoint__}
      - CLIENT_ENDPOINT=${__client_endpoint__}
      - SPOTIFY_PUBLIC=${__your_spotify_client_id__}
      - SPOTIFY_SECRET=${__your_spotify_secret__}
      - CORS=all
      - TIMEZONE=${TZ}
  mongo:
    container_name: mongo-your-spotify
    image: mongo:4.4.8
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/your_spotify/DB:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: unless-stopped
    ports:
      - "${__client_port__}:3000"
    environment:
      - API_ENDPOINT=${__api_endpoint__}
`
**Screenshots**

![image](https://github.com/Yooooomi/your_spotify/assets/36904646/877a29ab-2e2e-45a6-839c-4e9e30fe10c8)

Thanks

**Comment by Yooooomi** [comment]
Hello, have you tried restarting your backend? It seems that you have a song with no artist.

**Comment by MiisterChipsSs** [comment]
Hey, yeah evidently I try to restart everything

Le jeu. 26 oct. 2023 à 09:42, Timothee Boussus ***@***.***> a
écrit :

**Comment by Yooooomi** [comment]
Could you try erasing your database and restarting the backend afterwards. Just trying to see if this is spotify missing data or just the application getting in a weird state. Thanks
