### ISSUE TITLE
Error on server startup when using Free tier MongoAtlas cluster

### ISSUE THREAD

**Issue by SkYNewZ** [Yooooomi/your_spotify#324]
Running on a raspberrypi I don't want to run a local mongo instance.
So I'm using the free tier on MongoDB Atlas but the server can't after doing migrations successfully.

Here are logs from my container:
```$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb+srv://xx:yy@xxxx.mongodb.net/your_spotify?retryWrites=true
[info]  Connected to database !
[info]  Cannot read migrations from database. If this is the first time you run migrations, then this is normal.
/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:202
                callback(new error_1.MongoServerError(document));
                         ^

MongoServerError: {getParameter: 1, featureCompatibilityVersion: ""} not allowed in this atlas tier
    at Connection.onMessage (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:513:28) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  [Symbol(errorLabels)]: Set(0) {}
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

<img width="669" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/26750012/2155298f-5b33-4ef7-838d-eb3250b6c358">

**Comment by LeMABoule** [comment]
Hello !
I've the same same problem here. I do have the same logs as well ... I've tried with the [image ](https://docs.linuxserver.io/images/docker-your_spotify/) from linuxserver and it worked at the second connection attempt since it's looping through this error. However the classic Yooooomi/your_spotify image doesn't seems to loop through, so I get stuck at the first failed connection attempt, just like you...
