### ISSUE TITLE
Import: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by fbrinker** [Yooooomi/your_spotify#433]
**Description**

When importing my "Extended Streaming History", it seems that I have a corrupt entry in my dataset. All files work but one batch. It stops at 1850/16500, but I couldn't determine the entry yet.

**Log**
```
[info]  Importing... (1973/16500)
[info]  Adding The F Track - Showtek from data

[...]

[info]  Adding We're Doing It - Rob Bailey & The Hustle Standard from data
[error]  TypeError: Cannot read properties of null (reading 'id')
    at /app/apps/server/lib/tools/importers/full_privacy.js:140:59
    at Array.forEach (<anonymous>)
    at FullPrivacyImporter.<anonymous> (/app/apps/server/lib/tools/importers/full_privacy.js:138:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/apps/server/lib/tools/importers/full_privacy.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error]  This import failed, but metadata is kept so that you can retry it later in the settings
```

**Debugging**

Any idea what to look out for? The songs, the importer tries to add, have multiple occurrences in my file. Is the importer adding the tracks in the same order as they are listed in the file? So it would be an entry between object # 1850 and 1973?

**Comment by schumi4** [comment]
I'm also experiencing this with one of my json files.

**Comment by Murkless** [comment]
Yeah, me too. Any fix? I'm also running v1.12.0

**Comment by Yooooomi** [comment]
Hello, would you mind sharing it through discord at @yooooomi_ so I can have a look?

**Comment by schumi4** [comment]
> Hello, would you mind sharing it through discord at @yooooomi_ so I can have a look?

i added you on discord
