### ISSUE TITLE
Long import from privacy data fails when token expires

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#76]
**Describe the bug**
It seems that if it's taking a while to process the task queue of data, and token expires, it throws an error and fails to continue it.

**Expected behavior**
I expected it to be able to handle the token expiring by itself when searching for things.

**Additional context**
```
Feb 19 07:05:44 webapp-bullseye node[3983754]: [error]  Error: Request failed with status code 401
Feb 19 07:05:44 webapp-bullseye node[3983754]:     at createError (/var/www/9/samip537/sites/applications/spotify/your_spotify/server/node_modules/axios/lib/core/createError.js:16:15)
Feb 19 07:05:44 webapp-bullseye node[3983754]:     at settle (/var/www/9/samip537/sites/applications/spotify/your_spotify/server/node_modules/axios/lib/core/settle.js:17:12)
Feb 19 07:05:44 webapp-bullseye node[3983754]:     at IncomingMessage.handleStreamEnd (/var/www/9/samip537/sites/applications/spotify/your_spotify/server/node_modules/axios/lib/adapters/http.js:312:11)
Feb 19 07:05:44 webapp-bullseye node[3983754]:     at IncomingMessage.emit (node:events:532:35)
Feb 19 07:05:44 webapp-bullseye node[3983754]:     at endReadableNT (node:internal/streams/readable:1346:12)
Feb 19 07:05:44 webapp-bullseye node[3983754]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Feb 19 07:05:44 webapp-bullseye node[3983754]:   config: {
Feb 19 07:05:44 webapp-bullseye node[3983754]:     transitional: {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       silentJSONParsing: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       forcedJSONParsing: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       clarifyTimeoutError: false
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     adapter: [Function: httpAdapter],
Feb 19 07:05:44 webapp-bullseye node[3983754]:     transformRequest: [ [Function: transformRequest] ],
Feb 19 07:05:44 webapp-bullseye node[3983754]:     transformResponse: [ [Function: transformResponse] ],
Feb 19 07:05:44 webapp-bullseye node[3983754]:     timeout: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     xsrfCookieName: 'XSRF-TOKEN',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     xsrfHeaderName: 'X-XSRF-TOKEN',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     maxContentLength: -1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     maxBodyLength: -1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     validateStatus: [Function: validateStatus],
Feb 19 07:05:44 webapp-bullseye node[3983754]:     headers: {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       Accept: 'application/json, text/plain, */*',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'Content-Type': 'application/x-www-form-urlencoded',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       Authorization: 'Bearer BQASDX4gEWEb3ekrgelI19QsB2LTfh46H0HO87FLnos0l8fJ4ejXvNepnmqTtmSzRsi14SmZiRdE42_q4ByoIl-n3bg7drN3rJgdiN0yTUhw9-I8KR7IW2A8ctAbfTDUjd8k5p2jir8NgxU65jvPjgyNPfrV5q1fS_Wf4A',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'User-Agent': 'axios/0.25.0'
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     baseURL: 'https://api.spotify.com/v1',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     method: 'get',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     url: "/search?q=track:he's%20not%20you+artist:VERITE&type=track&limit=10",
Feb 19 07:05:44 webapp-bullseye node[3983754]:     data: undefined
Feb 19 07:05:44 webapp-bullseye node[3983754]:   },
Feb 19 07:05:44 webapp-bullseye node[3983754]:   request: <ref *1> ClientRequest {
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _events: [Object: null prototype] {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       abort: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       aborted: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       connect: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       error: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       socket: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       timeout: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       prefinish: [Function: requestOnPrefinish]
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _eventsCount: 7,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _maxListeners: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     outputData: [],
Feb 19 07:05:44 webapp-bullseye node[3983754]:     outputSize: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     writable: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     destroyed: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _last: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     chunkedEncoding: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     shouldKeepAlive: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     maxRequestsOnConnectionReached: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _defaultKeepAlive: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     useChunkedEncodingByDefault: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     sendDate: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _removedConnection: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _removedContLen: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _removedTE: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _contentLength: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _hasBody: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _trailer: '',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     finished: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _headerSent: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _closed: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     socket: TLSSocket {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _tlsOptions: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _secureEstablished: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _securePending: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _newSessionPending: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _controlReleased: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       secureConnecting: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _SNICallback: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       servername: 'api.spotify.com',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       alpnProtocol: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       authorized: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       authorizationError: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       encrypted: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _events: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _eventsCount: 10,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       connecting: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _hadError: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _parent: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _host: 'api.spotify.com',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _readableState: [ReadableState],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _maxListeners: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _writableState: [WritableState],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       allowHalfOpen: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _sockname: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _pendingData: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _pendingEncoding: '',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       server: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _server: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       ssl: [TLSWrap],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _requestCert: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _rejectUnauthorized: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       parser: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _httpMessage: [Circular *1],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(res)]: [TLSWrap],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(verified)]: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(pendingSession)]: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(async_id_symbol)]: 467283,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kHandle)]: [TLSWrap],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kSetNoDelay)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(lastWriteQueueSize)]: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(timeout)]: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kBuffer)]: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kBufferCb)]: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kBufferGen)]: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kCapture)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kBytesRead)]: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kBytesWritten)]: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(connect-options)]: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(RequestTimeout)]: undefined
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _header: 'GET /v1/search?q=track:he%27s%20not%20you+artist:VERITE&type=track&limit=10 HTTP/1.1\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'Accept: application/json, text/plain, */*\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'Content-Type: application/x-www-form-urlencoded\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'Authorization: Bearer BQASDX4gEWEb3ekrgelI19QsB2LTfh46H0HO87FLnos0l8fJ4ejXvNepnmqTtmSzRsi14SmZiRdE42_q4ByoIl-n3bg7drN3rJgdiN0yTUhw9-I8KR7IW2A8ctAbfTDUjd8k5p2jir8NgxU65jvPjgyNPfrV5q1fS_Wf4A\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'User-Agent: axios/0.25.0\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'Host: api.spotify.com\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'Connection: close\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:       '\r\n',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _keepAliveTimeout: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _onPendingData: [Function: nop],
Feb 19 07:05:44 webapp-bullseye node[3983754]:     agent: Agent {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _events: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _eventsCount: 2,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _maxListeners: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       defaultPort: 443,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       protocol: 'https:',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       options: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       requests: [Object: null prototype] {},
Feb 19 07:05:44 webapp-bullseye node[3983754]:       sockets: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       freeSockets: [Object: null prototype] {},
Feb 19 07:05:44 webapp-bullseye node[3983754]:       keepAliveMsecs: 1000,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       keepAlive: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxSockets: Infinity,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxFreeSockets: 256,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       scheduling: 'lifo',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxTotalSockets: Infinity,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       totalSocketCount: 1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxCachedSessions: 100,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _sessionCache: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kCapture)]: false
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     socketPath: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     method: 'GET',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     maxHeaderSize: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     insecureHTTPParser: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     path: '/v1/search?q=track:he%27s%20not%20you+artist:VERITE&type=track&limit=10',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _ended: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     res: IncomingMessage {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _readableState: [ReadableState],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _events: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _eventsCount: 4,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _maxListeners: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       socket: [TLSSocket],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       httpVersionMajor: 1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       httpVersionMinor: 1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       httpVersion: '1.1',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       complete: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       rawHeaders: [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       rawTrailers: [],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       aborted: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       upgrade: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       url: '',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       method: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       statusCode: 401,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       statusMessage: 'Unauthorized',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       client: [TLSSocket],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _consuming: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _dumped: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       req: [Circular *1],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       responseUrl: 'https://api.spotify.com/v1/search?q=track:he%27s%20not%20you+artist:VERITE&type=track&limit=10',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       redirects: [],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kCapture)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kHeaders)]: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kHeadersCount)]: 32,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kTrailers)]: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kTrailersCount)]: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(RequestTimeout)]: undefined
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     aborted: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     timeoutCb: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     upgradeOrConnect: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     parser: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     maxHeadersCount: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     reusedSocket: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     host: 'api.spotify.com',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     protocol: 'https:',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     _redirectable: Writable {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _writableState: [WritableState],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _events: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _eventsCount: 3,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _maxListeners: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _options: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _ended: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _ending: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _redirectCount: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _redirects: [],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _requestBodyLength: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _requestBodyBuffers: [],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _onNativeResponse: [Function (anonymous)],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _currentRequest: [Circular *1],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _currentUrl: 'https://api.spotify.com/v1/search?q=track:he%27s%20not%20you+artist:VERITE&type=track&limit=10',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kCapture)]: false
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     [Symbol(kCapture)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     [Symbol(kNeedDrain)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     [Symbol(corked)]: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     [Symbol(kOutHeaders)]: [Object: null prototype] {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       accept: [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'content-type': [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       authorization: [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'user-agent': [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       host: [Array]
Feb 19 07:05:44 webapp-bullseye node[3983754]:     }
Feb 19 07:05:44 webapp-bullseye node[3983754]:   },
Feb 19 07:05:44 webapp-bullseye node[3983754]:   response: {
Feb 19 07:05:44 webapp-bullseye node[3983754]:     status: 401,
Feb 19 07:05:44 webapp-bullseye node[3983754]:     statusText: 'Unauthorized',
Feb 19 07:05:44 webapp-bullseye node[3983754]:     headers: {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'www-authenticate': 'Bearer realm="spotify", error="invalid_token", error_description="The access token expired"',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'access-control-allow-origin': '*',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'access-control-allow-credentials': 'true',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'access-control-max-age': '604800',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'content-type': 'application/json',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'content-length': '81',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'strict-transport-security': 'max-age=31536000',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'x-content-type-options': 'nosniff',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       vary: 'Accept-Encoding',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       date: 'Sat, 19 Feb 2022 05:05:44 GMT',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       server: 'envoy',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       via: 'HTTP/2 edgeproxy, 1.1 google',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       'alt-svc': 'clear',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       connection: 'close'
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     config: {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       transitional: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       adapter: [Function: httpAdapter],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       transformRequest: [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       transformResponse: [Array],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       timeout: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       xsrfCookieName: 'XSRF-TOKEN',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       xsrfHeaderName: 'X-XSRF-TOKEN',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxContentLength: -1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxBodyLength: -1,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       validateStatus: [Function: validateStatus],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       headers: [Object],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       baseURL: 'https://api.spotify.com/v1',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       method: 'get',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       url: "/search?q=track:he's%20not%20you+artist:VERITE&type=track&limit=10",
Feb 19 07:05:44 webapp-bullseye node[3983754]:       data: undefined
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     request: <ref *1> ClientRequest {
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _events: [Object: null prototype],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _eventsCount: 7,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _maxListeners: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       outputData: [],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       outputSize: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       writable: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       destroyed: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _last: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       chunkedEncoding: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       shouldKeepAlive: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxRequestsOnConnectionReached: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _defaultKeepAlive: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       useChunkedEncodingByDefault: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       sendDate: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _removedConnection: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _removedContLen: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _removedTE: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _contentLength: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _hasBody: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _trailer: '',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       finished: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _headerSent: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _closed: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       socket: [TLSSocket],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _header: 'GET /v1/search?q=track:he%27s%20not%20you+artist:VERITE&type=track&limit=10 HTTP/1.1\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         'Accept: application/json, text/plain, */*\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         'Content-Type: application/x-www-form-urlencoded\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         'Authorization: Bearer BQASDX4gEWEb3ekrgelI19QsB2LTfh46H0HO87FLnos0l8fJ4ejXvNepnmqTtmSzRsi14SmZiRdE42_q4ByoIl-n3bg7drN3rJgdiN0yTUhw9-I8KR7IW2A8ctAbfTDUjd8k5p2jir8NgxU65jvPjgyNPfrV5q1fS_Wf4A\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         'User-Agent: axios/0.25.0\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         'Host: api.spotify.com\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         'Connection: close\r\n' +
Feb 19 07:05:44 webapp-bullseye node[3983754]:         '\r\n',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _keepAliveTimeout: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _onPendingData: [Function: nop],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       agent: [Agent],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       socketPath: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       method: 'GET',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxHeaderSize: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       insecureHTTPParser: undefined,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       path: '/v1/search?q=track:he%27s%20not%20you+artist:VERITE&type=track&limit=10',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _ended: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       res: [IncomingMessage],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       aborted: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       timeoutCb: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       upgradeOrConnect: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       parser: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       maxHeadersCount: null,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       reusedSocket: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       host: 'api.spotify.com',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       protocol: 'https:',
Feb 19 07:05:44 webapp-bullseye node[3983754]:       _redirectable: [Writable],
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kCapture)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kNeedDrain)]: false,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(corked)]: 0,
Feb 19 07:05:44 webapp-bullseye node[3983754]:       [Symbol(kOutHeaders)]: [Object: null prototype]
Feb 19 07:05:44 webapp-bullseye node[3983754]:     },
Feb 19 07:05:44 webapp-bullseye node[3983754]:     data: { error: [Object] }
Feb 19 07:05:44 webapp-bullseye node[3983754]:   },
Feb 19 07:05:44 webapp-bullseye node[3983754]:   isAxiosError: true,
Feb 19 07:05:44 webapp-bullseye node[3983754]:   toJSON: [Function: toJSON]
Feb 19 07:05:44 webapp-bullseye node[3983754]: }
```

**Comment by Yooooomi** [comment]
That's actually really weird, I ensure the token is valid before searching.
I do batches of 20 songs, and before this I verify if the token is valid for more than 2 minutes. I will check this out.
Many thanks for the feedback.

**Comment by Yooooomi** [comment]
Hey @samip5, did the one after worked fine, did it log something like `Refreshing token for ...`?

**Comment by Yooooomi** [comment]
I made so that it checks before every single request in the entire app, this should solve the problem. A bit more heavier but 100% stable I guess. I will push it by the end of the weekend since now I don't have time to check if I did not break anything.

**Comment by samip5** [comment]
> Hey @samip5, did the ones after worked fine, did it log something like `Refreshing token for ...`?

I did not see that at least even after the error I did not see any such thing in logs.

**Comment by samip5** [comment]
> I actually imported 17000 tracks without an issue smile

I'm trying to import `55635` tracks. :D

**Comment by Yooooomi** [comment]
> I'm trying to import `55635` tracks. :D

Ok you beat me 😂
The fix I'll push tomorrow or on Monday should help.

**Comment by Yooooomi** [comment]
Last release should fix this token issue. Could you please try to import your data again and see if you encounter any issue? Many thanks

**Comment by Yooooomi** [comment]
Have you been able to reproduce this issue @samip5?

**Comment by samip5** [comment]
> Have you been able to reproduce this issue @samip5?

No, this can be closed.
